//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkshopProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourseEnrollment
    {
        public int ClassEnrollmentID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Semester { get; set; }
        public Nullable<int> AcademicYear { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Student Student { get; set; }
    }
}
